// Generated by ReScript, PLEASE EDIT WITH CARE


var Button = {};

var Items = {};

var Item = {};

var Menu = {
  Button: Button,
  Items: Items,
  Item: Item
};

var Button$1 = {};

var Options = {};

var $$Option = {};

var Listbox = {
  Button: Button$1,
  Options: Options,
  $$Option: $$Option
};

var Transition = {};

var Group = {};

var List = {};

var Panels = {};

var Panel = {};

var Tab = {
  Group: Group,
  List: List,
  Panels: Panels,
  Panel: Panel
};

export {
  Menu ,
  Listbox ,
  Transition ,
  Tab ,
  
}
/* No side effect */
