// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as React$1 from "@headlessui/react";

function Index$Hero(Props) {
  var children = Props.children;
  return React.createElement("div", undefined, React.createElement("div", {
                  className: ""
                }, children));
}

var allCudaVersions = [
  "10.0",
  "10.1",
  "10.2",
  "11.0",
  "11.1",
  "11.2"
];

var builds = [
  "Stable",
  "Nightly"
];

function Index$Variant$Option(Props) {
  var name = Props.name;
  return React.createElement(React$1.Tab, {
              className: (function (param) {
                  return [
                            "w-full py-2.5 text-sm leading-5 font-medium rounded-lg",
                            "focus:outline-none focus:ring-2 ring-offset-2 ring-offset-blue-400 ring-white ring-opacity-60",
                            param.selected ? "bg-white shadow text-blue-700 text-opacity-80" : "text-blue-100 hover:bg-white hover:bg-opacity-10 hover:text-white"
                          ].join(" ");
                }),
              children: (function (param) {
                  return name;
                }),
              key: name
            });
}

function $$default(param) {
  var match = React.useState(function () {
        return Js_dict.fromArray([
                    [
                      "CUDA",
                      [
                        {
                          id: 1,
                          title: "python3 -m pip install -f https://release.oneflow.info oneflow==0.4.0+cu102",
                          date: "5h ago",
                          commentCount: 5,
                          shareCount: 2
                        },
                        {
                          id: 2,
                          title: "So you`ve bought coffee... now what?",
                          date: "2h ago",
                          commentCount: 3,
                          shareCount: 2
                        }
                      ]
                    ],
                    [
                      "CPU",
                      [
                        {
                          id: 1,
                          title: "Is tech making coffee better or worse?",
                          date: "Jan 7",
                          commentCount: 29,
                          shareCount: 16
                        },
                        {
                          id: 2,
                          title: "The most innovative things happening in coffee",
                          date: "Mar 19",
                          commentCount: 24,
                          shareCount: 12
                        }
                      ]
                    ],
                    [
                      "CUDA-XLA",
                      [
                        {
                          id: 1,
                          title: "Ask Me Anything: 10 answers to your questions about coffee",
                          date: "2d ago",
                          commentCount: 9,
                          shareCount: 5
                        },
                        {
                          id: 2,
                          title: "The worst advice we`ve ever heard about coffee",
                          date: "4d ago",
                          commentCount: 1,
                          shareCount: 2
                        }
                      ]
                    ]
                  ]);
      });
  var categories = match[0];
  return React.createElement(Index$Hero, {
              children: React.createElement("div", {
                    className: "rounded-xl overflow-hidden bg-gradient-to-r from-sky-400 to-blue-600 flex flex-col items-center justify-center w-full"
                  }, React.createElement("div", {
                        className: "w-full max-w-md px-2 py-16 sm:px-0"
                      }, React.createElement(React$1.Tab.Group, {
                            children: React.createElement(React$1.Tab.List, {
                                  children: (function (param) {
                                      return builds.map(function (category) {
                                                  return React.createElement(Index$Variant$Option, {
                                                              name: category
                                                            });
                                                });
                                    }),
                                  className: "flex p-1 space-x-1 bg-blue-900 bg-opacity-20 rounded-xl"
                                })
                          }), React.createElement(React$1.Tab.Group, {
                            children: React.createElement(React$1.Tab.List, {
                                  children: (function (param) {
                                      return Object.keys(categories).map(function (category) {
                                                  return React.createElement(Index$Variant$Option, {
                                                              name: category
                                                            });
                                                });
                                    }),
                                  className: "my-1 flex p-1 space-x-1 bg-blue-900 bg-opacity-20 rounded-xl"
                                })
                          }), React.createElement(React$1.Tab.Group, {
                            children: null
                          }, React.createElement(React$1.Tab.List, {
                                children: (function (param) {
                                    return allCudaVersions.map(function (category) {
                                                return React.createElement(Index$Variant$Option, {
                                                            name: category
                                                          });
                                              });
                                  }),
                                className: "flex p-1 space-x-1 bg-blue-900 bg-opacity-20 rounded-xl"
                              }), React.createElement(React$1.Tab.Panels, {
                                children: (function (param) {
                                    return Js_dict.values(categories).map(function (posts, idx) {
                                                return React.createElement(React$1.Tab.Panel, {
                                                            className: (function (param) {
                                                                return [
                                                                          "bg-white rounded-xl p-3",
                                                                          "focus:outline-none focus:ring-2 ring-offset-2 ring-offset-blue-400 ring-white ring-opacity-60"
                                                                        ].join(" ");
                                                              }),
                                                            children: (function (param) {
                                                                return Caml_array.get(posts, 0).title;
                                                              }),
                                                            key: String(idx)
                                                          });
                                              });
                                  }),
                                className: "mt-2"
                              }))))
            });
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
